global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "incidentiq-api"
    static_configs:
      - targets: ["api:8000"]

  - job_name: "incidentiq-worker"
    static_configs:
      - targets: ["worker:8001"]
  
  - job_name: "incidentiq-llm"
    metrics_path: /metrics
    static_configs:
      - targets: ["llm:8002"]
  
  - job_name: "incidentiq-broker-exporter"
    static_configs:
      - targets: ["broker-exporter:8003"]
