global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "incidentiq-api"
    static_configs:
      - targets: ["api:8000"]

  - job_name: "incidentiq-worker"
    static_configs:
      - targets: ["worker:8001"]